# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscore',
            old_name='score_data',
            new_name='score_date',
        ),
    ]
